// Products
export const GET_PRODUCTS_REQUESTED = "GET_PRODUCTS_REQUESTED";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const PRODUCTS_FAILED = "PRODUCTS_FAILED";
export const GET_SORT_NAME_REQUESTED = "GET_SORT_NAME_REQUESTED";
export const GET_SORT_NAME_SUCCESS = "GET_SORT_NAME_SUCCESS";
export const GET_SORT_VALUE_SUCCESS = "GET_SORT_VALUE_SUCCESS";
export const GET_SORT_COST_REQUESTED = "GET_SORT_COST_REQUESTED"