// Products
export const GET_PRODUCTS_REQUESTED = "GET_PRODUCTS_REQUESTED";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const PRODUCTS_FAILED = "PRODUCTS_FAILED";
export const GET_SORT_REQUESTED = "GET_SORT_REQUESTED"
export const GET_SORT_SUCCESS = "GET_SORT_SUCCESS"